-- Class codes for teacher-owned classrooms (parent approval happens when linking a student).
-- Safe to run multiple times.

-- 1) Ensure base table exists (some projects created it manually; this prevents hard failures).
create table if not exists public.classrooms (
  id bigint generated by default as identity primary key,
  name text not null,
  teacher_profile_id uuid,
  join_code text,
  created_at timestamptz not null default now()
);

-- 2) Add missing columns if table already existed
alter table if exists public.classrooms
  add column if not exists teacher_profile_id uuid;

alter table if exists public.classrooms
  add column if not exists join_code text;

alter table if exists public.classrooms
  add column if not exists created_at timestamptz not null default now();

-- 3) Unique join_code (case-insensitive)
create unique index if not exists classrooms_join_code_lower_uniq
  on public.classrooms (lower(join_code))
  where join_code is not null;

create index if not exists classrooms_teacher_profile_id_idx
  on public.classrooms (teacher_profile_id);

-- 4) RLS + policies
alter table public.classrooms enable row level security;

do $$
begin
  -- Teachers can CRUD their own classrooms.
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='classrooms' and policyname='teacher_select_own') then
    create policy teacher_select_own on public.classrooms
      for select
      to authenticated
      using (teacher_profile_id = auth.uid());
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='classrooms' and policyname='teacher_insert_own') then
    create policy teacher_insert_own on public.classrooms
      for insert
      to authenticated
      with check (teacher_profile_id = auth.uid());
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='classrooms' and policyname='teacher_update_own') then
    create policy teacher_update_own on public.classrooms
      for update
      to authenticated
      using (teacher_profile_id = auth.uid())
      with check (teacher_profile_id = auth.uid());
  end if;

  if not exists (select 1 from pg_policies where schemaname='public' and tablename='classrooms' and policyname='teacher_delete_own') then
    create policy teacher_delete_own on public.classrooms
      for delete
      to authenticated
      using (teacher_profile_id = auth.uid());
  end if;
end $$;


