-- Parent-approved class membership.
-- Safe to run multiple times.

create table if not exists public.classroom_students (
  id bigint generated by default as identity primary key,
  classroom_id bigint not null references public.classrooms(id) on delete cascade,
  student_id uuid references public.profiles(id) on delete cascade,
  parent_id uuid references public.profiles(id) on delete cascade,
  approved_at timestamptz,
  created_at timestamptz not null default now()
);

alter table if exists public.classroom_students
  add column if not exists student_id uuid;

alter table if exists public.classroom_students
  add column if not exists parent_id uuid;

alter table if exists public.classroom_students
  add column if not exists approved_at timestamptz;

alter table if exists public.classroom_students
  add column if not exists created_at timestamptz not null default now();

create index if not exists classroom_students_classroom_id_idx
  on public.classroom_students(classroom_id);

create index if not exists classroom_students_student_id_idx
  on public.classroom_students(student_id);

create index if not exists classroom_students_parent_id_idx
  on public.classroom_students(parent_id);

create unique index if not exists classroom_students_classroom_student_uniq
  on public.classroom_students(classroom_id, student_id)
  where student_id is not null;

alter table public.classroom_students enable row level security;

do $$
begin
  -- Parent can see their own links (pending + approved).
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='classroom_students' and policyname='parent_select_own') then
    create policy parent_select_own on public.classroom_students
      for select
      to authenticated
      using (parent_id = auth.uid());
  end if;

  -- Teacher can only see approved students for their own classrooms.
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='classroom_students' and policyname='teacher_select_approved') then
    create policy teacher_select_approved on public.classroom_students
      for select
      to authenticated
      using (
        approved_at is not null and
        exists (
          select 1
          from public.classrooms c
          where c.id = classroom_students.classroom_id
            and c.teacher_profile_id = auth.uid()
        )
      );
  end if;

  -- Parent can insert a link for their own child (must be in family_links).
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='classroom_students' and policyname='parent_insert_child') then
    create policy parent_insert_child on public.classroom_students
      for insert
      to authenticated
      with check (
        parent_id = auth.uid() and
        exists (
          select 1
          from public.family_links fl
          where fl.parent_id = auth.uid()
            and fl.child_id = classroom_students.student_id
        )
      );
  end if;

  -- Parent can update their own link (e.g. approve later).
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='classroom_students' and policyname='parent_update_own') then
    create policy parent_update_own on public.classroom_students
      for update
      to authenticated
      using (parent_id = auth.uid())
      with check (parent_id = auth.uid());
  end if;

  -- Teacher can delete students from their own classrooms (kick).
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='classroom_students' and policyname='teacher_delete_own') then
    create policy teacher_delete_own on public.classroom_students
      for delete
      to authenticated
      using (
        exists (
          select 1
          from public.classrooms c
          where c.id = classroom_students.classroom_id
            and c.teacher_profile_id = auth.uid()
        )
      );
  end if;
end $$;


